"""add gender to person

Revision ID: b692a8a03512
Revises: 6cd5dbaeaa4b
Create Date: 2023-12-18 23:54:03.777194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b692a8a03512'
down_revision = '6cd5dbaeaa4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
